AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run a static website with Apache Web Server
Resources:
  YagmurCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups: 
        - aa.yagmurr
      Tags:
        - Key: Name
          Value: Web server of Kittens Carousel
      UserData:
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 /var/www/html
          cd /var/www/html
          wget https://raw.githubusercontent.com/ipekyagmur/Project-101-Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/main/static-web/index.html
          wget https://raw.githubusercontent.com/ipekyagmur/Project-101-Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/main/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/ipekyagmur/Project-101-Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/main/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/ipekyagmur/Project-101-Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/main/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/ipekyagmur/Project-101-Kittens-Carousel-Static-Website-deployed-on-AWS-EC2-using-Cloudformation/main/static-web/cat3.png